#!/usr/bin/env bash
# Regenerate the Python bindings for the Android Emulator gRPC API from the vendored protos.
#
# The protos are staged under a directory tree that mirrors the target package, so the
# generated modules import each other as `hsai.emulator._proto.*` without post-processing.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
pkg="hsai/emulator/_proto"
out="$root/src"

staging="$(mktemp -d)"
trap 'rm -rf "$staging"' EXIT
mkdir -p "$staging/$pkg"
cp "$root"/third_party/android_emulator/*.proto "$staging/$pkg/"

rm -rf "${out:?}/$pkg"
mkdir -p "$out/$pkg"
# Running grpc_tools.protoc as a module adds the protobuf well-known types to the include path.
uv run --frozen python -m grpc_tools.protoc \
  -I "$staging" \
  --python_out="$out" \
  --pyi_out="$out" \
  --grpc_python_out="$out" \
  "$staging/$pkg"/*.proto
echo '"""Generated by scripts/gen_protos.sh. Do not edit."""' >"$out/$pkg/__init__.py"

echo "Generated bindings in src/$pkg"
